[theme]
base="light"
backgroundColor="#ffffff"  # White background
secondaryBackgroundColor="#d8d8d8"  # Light gray for sections
primaryColor="0041c2"  #  - for interactive elements
textColor="#323232"  # Ramboll dark gray - for text
font="sans serif"

# Additional custom styling
[server]
enableXsrfProtection=false  # If you're embedding the app